Profile: NZPSObservationPregnancyEDD    
Parent: http://hl7.org/fhir/uv/ips/StructureDefinition/Observation-pregnancy-edd-uv-ips
Id: nzps-observation-pregnancy-edd
Title: "NZPS-Observation-Pregnancy-EDD"
Description: "This profile constrains the Observation resource to represent the pregnancy expected delivery date."
* ^version = "0.1.0"
* ^status = #active

* subject only Reference ($nzps-patient)


